### ISSUE TITLE
Migration TODO

### ISSUE THREAD

**Issue by diegoferigo** [robotology/blockfactory#1]
The code hosted in this repository is the former core of [robotology/wb-toolbox](https://github.com/robotology/wb-toolbox). Most of the code was migrated with the first commits.

Here follows a list of remaining tasks to align this repository with the features of its parent:

- [x] Update the tlc file with the new headers folders and namespaces
- [x] Add Travis CI and Appveyor tests
- [x] Enable Codacy
- [x] Migrate the documentation
- [x] Update the doxygen documentation
- [x] Create a new ghpages-based website

**Comment by diegoferigo** [comment]
Finalized all the migration tasks. Closing.
